# Generated by Django 4.0.6 on 2022-10-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, db_column='imagen', null=True, upload_to='projects', verbose_name='Imagen')),
                ('titulodos', models.TextField(blank=True, db_column='tituloDos', null=True)),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'certificados',
                'managed': False,
            },
        ),
    ]
