# Generated by Django 4.0.6 on 2022-10-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('titulodos', models.TextField(blank=True, db_column='tituloDos', null=True)),
            ],
            options={
                'db_table': 'proyectos',
                'managed': False,
            },
        ),
    ]
